[phases.setup]
nixPkgs = ["python3", "ffmpeg-headless", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[variables]
# Environment variables should be set in deployment environment, not in config files

[start]
cmd = "python src/bot.py"